### ISSUE TITLE
Contact id

### ISSUE THREAD

**Issue by ecclesiastes4** [devaqto/domaincatcher#1]
Beste tamerciage,
Erg mooie tool! Wat moet ik invullen achter 'VERSIO_CONTACTID'?
Wat betekent 'VERSIO_ENDPOINT', '.nl')?

**Comment by ilyas013** [comment]
Het werkt niet. 
[25-08-2020 07:15:02] Domain registration for *mydomain.nl failed! [25-08-2020 07:15:02] All jobs done!
is er iemand die aan het werk heeft gekregen?
